### PR TITLE
User/ghaack/instr timings

### PR DESCRIPTION
**Pull request by granthaack**

### CODE REVIEW

**Comment by granthaack** [comment]
Getting the instruction timings down also requires a nearly cycle perfect timer. I've rewritten the timer so that it's as close to the original design of the game boy as possible. This will also make it easier to implement some of the bugs that are present in the GameBoy timer

Currently passing tests:
mooneye-gb suite:
- div_write
- tim00_div_trigger
- tim11_div_trigger

**Comment by granthaack** [comment]
More passing tests
mooneye-gb suite:

- boot_hwio-dmgABCmgb
- boot_regs-dmgABC

**Comment by blazer82** [comment]
Wow, this is great stuff! Well done! I take it you wanna keep going before creating a PR on my repo?

**Comment by blazer82** [comment]
On a side note: what editor/IDE are you using? Have you considered using a watcher to automatically clang-format your files on every save? That’s really a game changer once you get used to it. I tend to use similar tools with other languages, too. And.. your build would no longer fail 😊

**Comment by granthaack** [comment]
> Wow, this is great stuff! Well done! I take it you wanna keep going before creating a PR on my repo?

Yes, I'm doing a PR here so I can keep track of which tests are passing. I would recommend integrating the mooneye-gb tests in addition to Blargg. They're much more atomic and are very good about testing one thing. Blargg's instruction timing test still doesn't work because the timer is imperfect, but these will run regardless.

> On a side note: what editor/IDE are you using?
I am using VSCode. I'm certain there's a way to automatically have it clang format the files, I just haven't gotten around to it.

**Comment by blazer82** [comment]
>I am using VSCode.

Me too 😊 I can help you with that as soon as I’m back on my computer. 

>I would recommend integrating the mooneye-gb tests

Absolutely! I will create a badge for every single one of them! Was a good idea to pull them in. I started looking into them as well.

**Comment by granthaack** [comment]
Tests that now pass:

- tim00
- tim01
- tim10
- tim11
- tim01_div_trigger
- tim10_div_trigger

**Comment by blazer82** [comment]
Okay, so as for the format on save: You don't need any additional extensions. Just the default C/C++ extension and the in Settings -> Editor -> Formatting -> activate **Format On Save**

Or even easier: Cmd+Shift+P (on Mac) or Ctrl+Shift+P and then search for **format on save**

**Comment by granthaack** [comment]
> Okay, so as for the format on save: You don't need any additional extensions. Just the default C/C++ extension and the in Settings -> Editor -> Formatting -> activate **Format On Save**

Nice, I got it working. Thank you!

**Comment by granthaack** [comment]
the cpu_instr test uses the timer interrupt to test the EI instruction, and the timer interrupt is not working correctly

**Comment by granthaack** [comment]
Still working on this, won't have free time until the weekend

**Comment by blazer82** [comment]
In the meantime, I got Blargg‘s first APU tests to pass which also resulted in a 20% drop in performance, so I had to revert it 😅 can’t have accuracy but no performance 🤷‍♂️

**Comment by granthaack** [comment]
Yeah this instructions timing branch is slowing down execution as well. It dropped from 103% to 97%. What's the goal for this project? Are you going for accuracy or performance? There are plenty of well respected emulators out there that aren't perfect but still play 80% of games very well.

It's the 80/20 rule. 20% of the games will require fixes that cause 80% of the performance hit.

**Comment by blazer82** [comment]
My initial goal was to have it run Tetris and Super Mario Land and give a near perfect experience for these two. 

Technical accuracy was never a priority and neither was widespread support for other games because I think then you’re probably better off with a raspberry pi as the Teensy 4 just can’t deliver the required performance. 

I think everything close to 100% speed is acceptable now and some improvements can still be made later on.

**Pull request merged**
